version: '3'

services:
  jenkins:
    build:
      context: . #build的路徑
      dockerfile: Dockerfile #要build的dockerfile文件名
    ports:
      - '80:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - './jenkins_home/:/var/jenkins_home/'

